Draft agri services
ONDC-Official/ONDC-SRV-Specifications pull request #8
Opened 2024-04-23 05:01 UTC by AbhijeetONDC

Fixed according to previous MR comments

2024-04-24 08:49 UTC, tanyamadaan requested changes

2024-04-24 08:49 UTC, tanyamadaan commented on api/components/Examples/Agriculture_services/search/search_by_item.json
only live search is required in agri services?

2024-04-24 08:49 UTC, tanyamadaan commented on api/components/Examples/Agriculture_services/search/search_by_item.json
> +              "code": "BAP_TYPE"
Farmer is a BAP?

2024-04-24 08:49 UTC, tanyamadaan commented on api/components/Examples/Agriculture_services/search/search_by_item.json
> +                "start": "2024-04-04T22:00:00.000Z"
what does this range.start denotes?

2024-04-24 08:49 UTC, tanyamadaan commented on api/components/Examples/Agriculture_services/search/search_by_item_assaying.json
> +        "customer": {
why is customer number required in search?

2024-04-24 08:49 UTC, tanyamadaan commented on api/components/Examples/Agriculture_services/search/search_by_item_assaying.json
> +            "code": "COMMODITY_DETAILS"
what is the need of this? when the display is also false.

2024-04-29 03:40 UTC, tanya-ondc commented
Merging it as requested by Sumit.

2024-04-29 03:41 UTC, merged